print("I am prakash pariyar. this is my first python program")
print("name: Prakash Pariyar")
print("Address: Myagde 4, Tanahun")
print("Age: 29")
print("Job: Neplease Army")
print("लक्ष्य: एक कुशल प्रोगामर बन्ने")
print("Now In: Baglung")
print("Favourite Place: Pokhara")
print("aim "*5)
print("Five pluse Five is", 5+5)
print("Prakash Pariyar Name In Five Times:", "Prakash Pariyar. "*5)